App\Entity\Page:
    type: entity
    table: page
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToMany:
        taxonomies:
            targetEntity: App\Entity\Taxonomy
            cascade:
                - persist
            joinTable:
                name: page_to_taxonomy
                joinColumns:
                    page_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    taxonomy_id:
                        referencedColumnName: id
                        onDelete: CASCADE

    fields:
        name:
            nullable: false
        published:
            type: boolean
            options:
                default: 0