App\Entity\Taxonomy:
    type: entity
    table: taxonomy
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    uniqueConstraints:
        name_idx:
            columns: [name]

    fields:
        name: